project_id = "qlkhlcoyrifbvzbqkshu"

[functions.fetch-teams]
verify_jwt = false

[functions.fetch-events]
verify_jwt = false

[functions.fetch-game-settings]
verify_jwt = false

[functions.fetch-element-types]
verify_jwt = false

[functions.fetch-chips]
verify_jwt = false

[functions.fetch-players]
verify_jwt = false

[functions.fetch-scoring-rules]
verify_jwt = false